name: insanberbagi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  firebase_core : 
  firebase_auth: 
  cloud_firestore: 
  firebase_storage: 
  flutter_native_splash: ^2.2.3
  smooth_page_indicator: ^1.1.0
  image_picker : ^0.8.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/




