// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm7GH1PVmuGyQQEUz7xOkRt9UqHAJt99A',
    appId: '1:733095552464:web:42cb891c9ff3dc039ac5d5',
    messagingSenderId: '733095552464',
    projectId: 'insanberbagi-b9cbf',
    authDomain: 'insanberbagi-b9cbf.firebaseapp.com',
    storageBucket: 'insanberbagi-b9cbf.appspot.com',
    measurementId: 'G-2R1E775FNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWzPjE7Eu8Ub8OIVB_3FHqBrnqQuvJiF8',
    appId: '1:733095552464:android:090869a38330aee99ac5d5',
    messagingSenderId: '733095552464',
    projectId: 'insanberbagi-b9cbf',
    storageBucket: 'insanberbagi-b9cbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP2xZou_X_z00_VrWEPy10LVGNwTAMHME',
    appId: '1:733095552464:ios:c8f44f791ece0bcd9ac5d5',
    messagingSenderId: '733095552464',
    projectId: 'insanberbagi-b9cbf',
    storageBucket: 'insanberbagi-b9cbf.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP2xZou_X_z00_VrWEPy10LVGNwTAMHME',
    appId: '1:733095552464:ios:b3c7401058f563e69ac5d5',
    messagingSenderId: '733095552464',
    projectId: 'insanberbagi-b9cbf',
    storageBucket: 'insanberbagi-b9cbf.appspot.com',
    iosBundleId: 'com.example.newproject.RunnerTests',
  );
}
